
###
GET http://localhost:2000/api/equipos/2022
Content-Type: application/json
###
GET http://localhost:2000/api/info-torneo/2022/2012
Content-Type: application/json

##Para crear las zonas
###
GET http://localhost:2000/api/info-torneo/create/2022/2012
Content-Type: application/json

###
GET http://localhost:2000/api/fase-grupos/2022/2013
Content-Type: application/json


###
GET https://humbertito.online/api/fase-grupos/2022/2013


##Para crear no competitivo 2016
###
GET http://localhost:2000/api/no-competitivo/create/2022/2016
Content-Type: application/json

###
GET http://localhost:2000/api/no-competitivo/2022/2016
Content-Type: application/json
