
###
GET http://localhost:2000/api/equipos/2023
Content-Type: application/json
###
GET http://localhost:2000/api/info-torneo/2023/2015
Content-Type: application/json

##Para crear las zonas
###
GET http://localhost:2000/api/info-torneo/create/2023/2016
Content-Type: application/json

###
GET http://localhost:2000/api/fase-grupos/2023/2013
Content-Type: application/json


###
GET https://humbertito.online/api/fase-grupos/2023/2014


##Para crear no competitivo 2016
###
GET http://localhost:2000/api/no-competitivo/create/2022/2016
Content-Type: application/json

###
GET http://localhost:2000/api/no-competitivo/2022/2016
Content-Type: application/json
